apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elk
spec:
  version: 8.6.2
  count: 1
  elasticsearchRef:
    name: elastic-cluster
  config:
    server.publicBaseUrl: "https://dev-kibana.opaz.me"
    csp.strict: false
  podTemplate:
    spec:
      priorityClassName: elastic-cluster-high-priority
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2.5Gi
              cpu: 2
