apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
  - repoURL: 'repo-url'
    targetRevision: HEAD
    path: overlay/test/loki-stack

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true